---
- name: Example Ansible Playbook for Handler
  hosts: all
  remote_user: ubuntu
  roles:
    - handler

  handlers:
    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted